// exercise: produce
// the following image:
// 
// ........o........
// .......ooo.......
// ......ooooo......
// .....ooooooo.....
// ....ooooooooo....
// ...ooooooooooo...
// ..ooooooooooooo..
// .ooooooooooooooo.
// ooooooooooooooooo